### ISSUE TITLE
Uniforms props are not updated, they always use the first value that is given

### ISSUE THREAD

**Issue by Prinzhorn** [regl-project/regl#467] opened 2018-03-26 08:54 UTC
Given the first example from the README (which I believe is broken as well, I replaced `time` with `Date.now()`)

```js
// Calling the regl module with no arguments creates a full screen canvas and
// WebGL context, and then uses this context to initialize a new REGL instance
const regl = require('regl')()

// Calling regl() creates a new partially evaluated draw command
const drawTriangle = regl({

  // Shaders in regl are just strings.  You can use glslify or whatever you want
  // to define them.  No need to manually create shader objects.
  frag: `
    precision mediump float;
    uniform vec4 color;
    void main() {
      gl_FragColor = color;
    }`,

  vert: `
    precision mediump float;
    attribute vec2 position;
    void main() {
      gl_Position = vec4(position, 0, 1);
    }`,

  // Here we define the vertex attributes for the above shader
  attributes: {
    // regl.buffer creates a new array buffer object
    position: regl.buffer([
      [-2, -2],   // no need to flatten nested arrays, regl automatically
      [4, -2],    // unrolls them into a typedarray (default Float32)
      [4,  4]
    ])
    // regl automatically infers sane defaults for the vertex attribute pointers
  },

  uniforms: {
    // This defines the color of the triangle to be a dynamic variable
    color: regl.prop('color')
  },

  // This tells regl the number of vertices to draw in this command
  count: 3
})

// regl.frame() wraps requestAnimationFrame and also handles viewport changes
regl.frame(({time}) => {
  // clear contents of the drawing buffer
  regl.clear({
    color: [0, 0, 0, 0],
    depth: 1
  })

  // draw a triangle using the command defined above
  drawTriangle({
    color: [
      Math.cos(Date.now() * 0.001),
      Math.sin(Date.now() * 0.0008),
      Math.cos(Date.now() * 0.003),
      1
    ]
  })
})
```

This renders a triangle that is ever changing in color. If we use the draw function twice and first render the triangle red:

```js
// regl.frame() wraps requestAnimationFrame and also handles viewport changes
regl.frame(() => {
  // clear contents of the drawing buffer
  regl.clear({
    color: [0, 0, 0, 0],
    depth: 1
  })

  drawTriangle({
    color: [
      1,
      0,
      0,
      1
    ]
  })

  // draw a triangle using the command defined above
  drawTriangle({
    color: [
      Math.cos(Date.now() * 0.001),
      Math.sin(Date.now() * 0.0008),
      Math.cos(Date.now() * 0.003),
      1
    ]
  })
})
```

the triangle is now always red. The second draw uses the old `color` prop. The same is true for batching

```js
// regl.frame() wraps requestAnimationFrame and also handles viewport changes
regl.frame(() => {
  // clear contents of the drawing buffer
  regl.clear({
    color: [0, 0, 0, 0],
    depth: 1
  })

  // draw a triangle using the command defined above
  drawTriangle({
    color: [
      1,
      0,
      0,
      1
    ]
  }, {
    color: [
      Math.cos(Date.now() * 0.001),
      Math.sin(Date.now() * 0.0008),
      Math.cos(Date.now() * 0.003),
      1
    ]
  })
})
```

**Comment by rreusser** [comment] 2018-05-16 23:08
@Prinzhorn I believe the issue is that the depth testing is enabled so that the first triangle (the red one) sets the depth in the depth buffer and the second test (the one with changing color) fails the depth test as a result. A fix is to add `depth: {enable: false}` to the original command. Then the colored triangle *does* get drawn. Closing this issue, but please feel free to follow up with questions/comments!

**Closed by rreusser** 2018-05-16 23:08 UTC

**Comment by rreusser** [comment] 2018-05-17 15:02
It's surprising at first 😄 If you always just want last on top, you can disable depth for the main drawing buffer in the [context creation attributes](https://github.com/regl-project/regl/blob/master/API.md#all-initialization-options) (it's a little hidden!), though it's equivalent. No realistic performance difference, I'd think.

**Comment by Prinzhorn** [comment] 2018-05-18 09:33
Thanks again. I'm trying to get into the mindset I was two months ago and I'm playing with my actual code, not the example above. You can see it in action here https://www.scrollmeister.com/demos/the-slim-shaders-lp.html

Under certain circumstances the image does not update and it looks like depth doesn't have anything to do with it. However, adding a `clear` call does (which I previously didn't have).

Help me understand this. I'm drawing a single triangle that fills the entire canvas (which uses a shader to manipulate a texture). I didn't `clear` the canvas before drawing because there is no alpha involved and I thought everything would be drawn over anyway. Clearing does fix it, but I try to understand why.

I'm currently initializing regl like this

```js
regl = createRegl({
	canvas: this._canvas,
	depth: {
		enable: false
	}
});
```

is this correct to disable depth testing?

My render loop does this

```js
regl.poll();

draw({
	image: this._texture,
	progress: interpolateBehavior.values.progress,
	size: [this._canvas.width, this._canvas.height]
});
```

if I add `regl.clear` before `draw` it is always updated correctly, regardless of the depth setting.

**Comment by Prinzhorn** [comment] 2018-05-18 14:33
Works perfectly, thank you for your time!

As a feature request it would be awesome to validate the arguments in --debug mode. Similar to how react validates propTypes only in development. Maybe sth. like https://github.com/sindresorhus/ow ? Not sure if it does validation of object keys (e.g. reject object that have unknown keys)

**Comment by rreusser** [comment] 2018-05-18 16:00
No prob! Yeah, I got caught off guard when I realized command parameters are checked while others are not. Fortunately, the docs are very good so that it's not too necesary, though it would be nice. See: https://github.com/regl-project/regl/issues/397
