### ISSUE TITLE
Setup framebuffer directly

### ISSUE THREAD

**Issue by dfcreative** [regl-project/regl#417] opened 2017-06-11 17:48 UTC
For now setting up framebuffer requires a separate call before drawing.
That would be intuitive to be able to call it directly:

```js
const regl =  require('regl')({
  extensions: ['OES_texture_float'],
  optionalExtensions: ['oes_texture_float_linear']
})

let draw = regl({
  framebuffer: regl.framebuffer({radius: 256, colorType: 'float', colorFormat: 'rgba'}),

  vert: `
  attribute vec2 position;
  void main () {
    gl_Position = vec4(position, 0, 1);
  }
  `,
  frag: `void main () {gl_FragColor = vec4(1,1,1,1);}`,
  count: 3,
  attributes: {position: [-1,-1, -1,3, 3,-1]},
  primitive: 'triangles'
})

//direct draw
draw()
regl.read({data: new Float32Array(256*256*4)})
```

Because for now it is a bit confusing
```js
draw(() => {
  //how this draw is different?
  draw()
  regl.read({data: new Float32Array(256*256*4)})
})
```

**Comment by jwerle** [comment] 2017-08-23 16:59
Instead of binding the `framebuffer` directly to the command, create and use an instance directly with the draw command scoped to it by creating a command that injects a framebuffer, or use the `framebuffer.use()` method to provide a scope.


See [this](http://requirebin.com/?gist=c80f40485bc24b4aa683b1c2507d6df2) or check out the snippet below

```js
const regl =  require('regl')({
  extensions: ['OES_texture_float'],
  optionalExtensions: ['oes_texture_float_linear']
})

const framebuffer = regl.framebuffer({colorType: 'float', colorFormat: 'rgba'})
const framebufferCommand = regl({framebuffer})

let draw = regl({
  vert: `
  attribute vec2 position;
  void main () {
    gl_Position = vec4(position, 0, 1);
  }
  `,
  frag: `void main () {gl_FragColor = vec4(1,1,1,1);}`,
  count: 3,
  attributes: {position: [-1,-1, -1,3, 3,-1]},
  primitive: 'triangles'
})

const data = new Float32Array(256*256*4)
framebuffer.use(() => {
  draw()
  regl.read({data})
})
  
// or
framebufferCommand(() => {
  draw()
  regl.read({data})
})
  
  console.log(data)

```

**Comment by jwerle** [comment] 2017-08-23 17:00
I removed the `radius` argument to the `framebuffer` constructor as it only applied to a cubic framebuffer

**Comment by dfcreative** [comment] 2017-08-23 17:07
@jwerle thanks for the explanation, that is better than docs :). I just imagined that API could be done to be a bit more intuitive. if `draw` accepted a `framebuffer` just as a property for a single `draw` call. So that user could render to a screen as `draw({...})` or to framebuffer as `draw({fb, ...})`. Things like `framebuffer.use()` make stateful API, which is no different from pure webgl or stack.gl.

**Comment by jwerle** [comment] 2017-08-23 18:03
Yeah we make simple use of it in axis3d
https://github.com/littlstar/axis3d/blob/master/src/framebuffer/framebuffer.js
https://github.com/littlstar/axis3d/blob/master/example/framebuffer/index.js#L207

alternatively, you can set the `framebuffer` on the draw command as a function to be dynamic and read from the command properties


```js
const regl =  require('regl')({
  extensions: ['OES_texture_float'],
  optionalExtensions: ['oes_texture_float_linear'],
})

const fbo = regl.framebuffer({colorType: 'float', colorFormat: 'rgba'})
const inject = regl({framebuffer: fbo})
const draw = regl({
  framebuffer(ctx, props) {
    if (props && 'framebuffer' in props) {
      return props.framebuffer
    }
    // otherwise the drawing buffer or any
    // contextually bound framebuffer injected into the context
  },

 vert: `
  attribute vec2 position;
  void main () { gl_Position = vec4(position, 0, 1); }
  `,
  frag: `void main () {gl_FragColor = vec4(1,1,1,1);}`,
  count: 3,
  attributes: {position: [-1,-1, -1,3, 3,-1]},
  primitive: 'triangles'
})

const data = new Float32Array(256*256*4)
draw()
draw({framebuffer: fbo})
inject(() => {
  // the framebuffer given to the second draw() call is bound
  // and can be read from with regl.read()
  regl.read({data})
})

console.log(data)
```

**Comment by mikolalysenko** [comment] 2018-01-11 21:14
Going to close this, currently the API is working as intended.

**Closed by mikolalysenko** 2018-01-11 21:14 UTC
